
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace ET
{
public partial class AIConfigCategory
{
    private readonly System.Collections.Generic.Dictionary<int, AIConfig> _dataMap;
    private readonly System.Collections.Generic.List<AIConfig> _dataList;
    
    public AIConfigCategory(ByteBuf _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, AIConfig>();
        _dataList = new System.Collections.Generic.List<AIConfig>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            AIConfig _v;
            _v = global::ET.AIConfig.DeserializeAIConfig(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, AIConfig> DataMap => _dataMap;
    public System.Collections.Generic.List<AIConfig> DataList => _dataList;

    public AIConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public AIConfig Get(int key) => _dataMap[key];
    public AIConfig this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

