
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace ET
{
public partial struct BatchInfo
{
    public BatchInfo(ByteBuf _buf) 
    {
        SpawnId = _buf.ReadInt();
        SpawnId_Ref = null;
        Delay = _buf.ReadInt();
    }

    public static BatchInfo DeserializeBatchInfo(ByteBuf _buf)
    {
        return new BatchInfo(_buf);
    }

    public readonly int SpawnId;
    public SpawnConfig SpawnId_Ref;
    public readonly int Delay;
   

    public  void ResolveRef(Tables tables)
    {
        SpawnId_Ref = tables.SpawnConfigCategory.GetOrDefault(SpawnId);
    }

    public override string ToString()
    {
        return "{ "
        + "SpawnId:" + SpawnId + ","
        + "Delay:" + Delay + ","
        + "}";
    }
}

}

