
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace ET
{
public partial class BattleGlobalConfigCategory
{

     private readonly BattleGlobalConfig _data;

     public BattleGlobalConfig Data => _data;

    public BattleGlobalConfigCategory(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        if (n != 1) throw new SerializationException("table mode=one, but size != 1");
        _data = global::ET.BattleGlobalConfig.DeserializeBattleGlobalConfig(_buf);
    }


    /// <summary>
    /// SlotSpacing
    /// </summary>
     public float SlotSpacing => _data.SlotSpacing;
    /// <summary>
    /// Description
    /// </summary>
     public string Description => _data.Description;
    
}

}

