
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace ET
{
public partial class BuffConfigCategory
{
    private readonly System.Collections.Generic.Dictionary<int, BuffConfig> _dataMap;
    private readonly System.Collections.Generic.List<BuffConfig> _dataList;
    
    public BuffConfigCategory(ByteBuf _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, BuffConfig>();
        _dataList = new System.Collections.Generic.List<BuffConfig>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            BuffConfig _v;
            _v = global::ET.BuffConfig.DeserializeBuffConfig(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, BuffConfig> DataMap => _dataMap;
    public System.Collections.Generic.List<BuffConfig> DataList => _dataList;

    public BuffConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public BuffConfig Get(int key) => _dataMap[key];
    public BuffConfig this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

