
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace ET
{
public partial class BuffGroupConfigCategory
{
    private readonly System.Collections.Generic.Dictionary<int, BuffGroupConfig> _dataMap;
    private readonly System.Collections.Generic.List<BuffGroupConfig> _dataList;
    
    public BuffGroupConfigCategory(ByteBuf _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, BuffGroupConfig>();
        _dataList = new System.Collections.Generic.List<BuffGroupConfig>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            BuffGroupConfig _v;
            _v = global::ET.BuffGroupConfig.DeserializeBuffGroupConfig(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, BuffGroupConfig> DataMap => _dataMap;
    public System.Collections.Generic.List<BuffGroupConfig> DataList => _dataList;

    public BuffGroupConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public BuffGroupConfig Get(int key) => _dataMap[key];
    public BuffGroupConfig this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

