
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace ET
{
/// <summary>
/// 发射器升级配置
/// </summary>
public partial class EmitterUpgradeConfigCategory
{
    private readonly System.Collections.Generic.Dictionary<int, EmitterUpgradeConfig> _dataMap;
    private readonly System.Collections.Generic.List<EmitterUpgradeConfig> _dataList;
    
    public EmitterUpgradeConfigCategory(ByteBuf _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, EmitterUpgradeConfig>();
        _dataList = new System.Collections.Generic.List<EmitterUpgradeConfig>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            EmitterUpgradeConfig _v;
            _v = global::ET.EmitterUpgradeConfig.DeserializeEmitterUpgradeConfig(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, EmitterUpgradeConfig> DataMap => _dataMap;
    public System.Collections.Generic.List<EmitterUpgradeConfig> DataList => _dataList;

    public EmitterUpgradeConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public EmitterUpgradeConfig Get(int key) => _dataMap[key];
    public EmitterUpgradeConfig this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

