
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace ET
{
public sealed partial class EmitterEffectConfig : Luban.BeanBase
{
    public EmitterEffectConfig(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Name = _buf.ReadString();
        EffectKind = _buf.ReadInt();
        TargetStat = _buf.ReadInt();
        ModifyOp = _buf.ReadInt();
        Value = _buf.ReadFloat();
        BuffGroupId = _buf.ReadInt();
        Desc = _buf.ReadString();
    }

    public static EmitterEffectConfig DeserializeEmitterEffectConfig(ByteBuf _buf)
    {
        return new EmitterEffectConfig(_buf);
    }

    /// <summary>
    /// 效果ID
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 效果名称
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 效果类型：1=修饰发射器属性，2=命中应用BuffGroup
    /// </summary>
    public readonly int EffectKind;
    /// <summary>
    /// 目标属性：1=CooldownMs，2=Range，3=WhiteDamage，4=BaseDamage
    /// </summary>
    public readonly int TargetStat;
    /// <summary>
    /// 修改方式：1=Add，2=Multiply，3=Override
    /// </summary>
    public readonly int ModifyOp;
    /// <summary>
    /// 修改值
    /// </summary>
    public readonly float Value;
    /// <summary>
    /// Buff组ID
    /// </summary>
    public readonly int BuffGroupId;
    /// <summary>
    /// 描述
    /// </summary>
    public readonly string Desc;
   
    public const int __ID__ = 1315117729;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "Name:" + Name + ","
        + "EffectKind:" + EffectKind + ","
        + "TargetStat:" + TargetStat + ","
        + "ModifyOp:" + ModifyOp + ","
        + "Value:" + Value + ","
        + "BuffGroupId:" + BuffGroupId + ","
        + "Desc:" + Desc + ","
        + "}";
    }
}

}

