
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace ET
{
/// <summary>
/// 发射器效果包配置
/// </summary>
public partial class EmitterEffectPackConfigCategory
{
    private readonly System.Collections.Generic.Dictionary<int, EmitterEffectPackConfig> _dataMap;
    private readonly System.Collections.Generic.List<EmitterEffectPackConfig> _dataList;
    
    public EmitterEffectPackConfigCategory(ByteBuf _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, EmitterEffectPackConfig>();
        _dataList = new System.Collections.Generic.List<EmitterEffectPackConfig>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            EmitterEffectPackConfig _v;
            _v = global::ET.EmitterEffectPackConfig.DeserializeEmitterEffectPackConfig(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, EmitterEffectPackConfig> DataMap => _dataMap;
    public System.Collections.Generic.List<EmitterEffectPackConfig> DataList => _dataList;

    public EmitterEffectPackConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public EmitterEffectPackConfig Get(int key) => _dataMap[key];
    public EmitterEffectPackConfig this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

