
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace ET
{
public sealed partial class EmitterUpgradeConfig : Luban.BeanBase
{
    public EmitterUpgradeConfig(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        UpgradeConfigId = _buf.ReadInt();
        Level = _buf.ReadInt();
        Code = _buf.ReadString();
        Name = _buf.ReadString();
        CooldownReduceMs = _buf.ReadInt();
        RangeAdd = _buf.ReadFloat();
        WhiteDamageMultiplier = _buf.ReadFloat();
        Desc = _buf.ReadString();
    }

    public static EmitterUpgradeConfig DeserializeEmitterUpgradeConfig(ByteBuf _buf)
    {
        return new EmitterUpgradeConfig(_buf);
    }

    /// <summary>
    /// 升级等级配置ID
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 升级方案ID
    /// </summary>
    public readonly int UpgradeConfigId;
    /// <summary>
    /// 等级
    /// </summary>
    public readonly int Level;
    /// <summary>
    /// 代码名
    /// </summary>
    public readonly string Code;
    /// <summary>
    /// 名称
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 累计减少冷却毫秒
    /// </summary>
    public readonly int CooldownReduceMs;
    /// <summary>
    /// 累计增加射程
    /// </summary>
    public readonly float RangeAdd;
    /// <summary>
    /// 白值伤害倍率
    /// </summary>
    public readonly float WhiteDamageMultiplier;
    /// <summary>
    /// 描述
    /// </summary>
    public readonly string Desc;
   
    public const int __ID__ = -994758704;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "UpgradeConfigId:" + UpgradeConfigId + ","
        + "Level:" + Level + ","
        + "Code:" + Code + ","
        + "Name:" + Name + ","
        + "CooldownReduceMs:" + CooldownReduceMs + ","
        + "RangeAdd:" + RangeAdd + ","
        + "WhiteDamageMultiplier:" + WhiteDamageMultiplier + ","
        + "Desc:" + Desc + ","
        + "}";
    }
}

}

