
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace ET
{
public sealed partial class EmitterConfig : Luban.BeanBase
{
    public EmitterConfig(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Name = _buf.ReadString();
        EmitterKind = _buf.ReadInt();
        CastType = _buf.ReadInt();
        TargetType = _buf.ReadInt();
        TargetingConfigId = _buf.ReadInt();
        TargetingConfigId_Ref = null;
        CooldownGroupId = _buf.ReadInt();
        CooldownMs = _buf.ReadInt();
        Priority = _buf.ReadInt();
        CanMoveCast = _buf.ReadBool();
        NeedExplicitTarget = _buf.ReadBool();
        IsEnabled = _buf.ReadBool();
        ProjectileSpeed = _buf.ReadFloat();
        ProjectileMaxDistance = _buf.ReadFloat();
        ProjectileCollisionRadius = _buf.ReadFloat();
        ProjectilePiercing = _buf.ReadBool();
        ProjectileMaxHitCount = _buf.ReadInt();
        Desc = _buf.ReadString();
        AttackHitRatio = _buf.ReadFloat();
        UpgradeConfigId = _buf.ReadInt();
        BuffSlotCount = _buf.ReadInt();
        BaseDamage = _buf.ReadFloat();
        WhiteAttackRatio = _buf.ReadFloat();
    }

    public static EmitterConfig DeserializeEmitterConfig(ByteBuf _buf)
    {
        return new EmitterConfig(_buf);
    }

    /// <summary>
    /// 发射器ID
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 发射器名称
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 发射器类型
    /// </summary>
    public readonly int EmitterKind;
    /// <summary>
    /// 发射方式
    /// </summary>
    public readonly int CastType;
    /// <summary>
    /// 目标类型
    /// </summary>
    public readonly int TargetType;
    /// <summary>
    /// 目标配置ID
    /// </summary>
    public readonly int TargetingConfigId;
    public SkillTargetingConfig TargetingConfigId_Ref;
    /// <summary>
    /// 冷却组ID
    /// </summary>
    public readonly int CooldownGroupId;
    /// <summary>
    /// 冷却毫秒
    /// </summary>
    public readonly int CooldownMs;
    /// <summary>
    /// 优先级
    /// </summary>
    public readonly int Priority;
    /// <summary>
    /// 是否可移动施法
    /// </summary>
    public readonly bool CanMoveCast;
    /// <summary>
    /// 是否必须显式指定目标
    /// </summary>
    public readonly bool NeedExplicitTarget;
    /// <summary>
    /// 是否启用
    /// </summary>
    public readonly bool IsEnabled;
    /// <summary>
    /// 投射物飞行速度（单位/秒）
    /// </summary>
    public readonly float ProjectileSpeed;
    /// <summary>
    /// 投射物最大飞行距离
    /// </summary>
    public readonly float ProjectileMaxDistance;
    /// <summary>
    /// 投射物碰撞半径
    /// </summary>
    public readonly float ProjectileCollisionRadius;
    /// <summary>
    /// 投射物是否穿透
    /// </summary>
    public readonly bool ProjectilePiercing;
    /// <summary>
    /// 投射物最大命中单位数
    /// </summary>
    public readonly int ProjectileMaxHitCount;
    /// <summary>
    /// 描述
    /// </summary>
    public readonly string Desc;
    /// <summary>
    /// 攻击动画命中点比例
    /// </summary>
    public readonly float AttackHitRatio;
    /// <summary>
    /// 升级方案ID
    /// </summary>
    public readonly int UpgradeConfigId;
    /// <summary>
    /// Buff槽位数量
    /// </summary>
    public readonly int BuffSlotCount;
    /// <summary>
    /// 白值基础伤害
    /// </summary>
    public readonly float BaseDamage;
    /// <summary>
    /// 白值攻击力系数
    /// </summary>
    public readonly float WhiteAttackRatio;
   
    public const int __ID__ = -2062774224;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        TargetingConfigId_Ref = tables.SkillTargetingConfigCategory.GetOrDefault(TargetingConfigId);
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "Name:" + Name + ","
        + "EmitterKind:" + EmitterKind + ","
        + "CastType:" + CastType + ","
        + "TargetType:" + TargetType + ","
        + "TargetingConfigId:" + TargetingConfigId + ","
        + "CooldownGroupId:" + CooldownGroupId + ","
        + "CooldownMs:" + CooldownMs + ","
        + "Priority:" + Priority + ","
        + "CanMoveCast:" + CanMoveCast + ","
        + "NeedExplicitTarget:" + NeedExplicitTarget + ","
        + "IsEnabled:" + IsEnabled + ","
        + "ProjectileSpeed:" + ProjectileSpeed + ","
        + "ProjectileMaxDistance:" + ProjectileMaxDistance + ","
        + "ProjectileCollisionRadius:" + ProjectileCollisionRadius + ","
        + "ProjectilePiercing:" + ProjectilePiercing + ","
        + "ProjectileMaxHitCount:" + ProjectileMaxHitCount + ","
        + "Desc:" + Desc + ","
        + "AttackHitRatio:" + AttackHitRatio + ","
        + "UpgradeConfigId:" + UpgradeConfigId + ","
        + "BuffSlotCount:" + BuffSlotCount + ","
        + "BaseDamage:" + BaseDamage + ","
        + "WhiteAttackRatio:" + WhiteAttackRatio + ","
        + "}";
    }
}

}

