
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace ET
{
public sealed partial class EmitterEffectPackConfig : Luban.BeanBase
{
    public EmitterEffectPackConfig(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Name = _buf.ReadString();
        {int __n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);EffectIds = new int[__n0];for(var __index0 = 0 ; __index0 < __n0 ; __index0++) { int __e0;__e0 = _buf.ReadInt(); EffectIds[__index0] = __e0;}}
        Desc = _buf.ReadString();
    }

    public static EmitterEffectPackConfig DeserializeEmitterEffectPackConfig(ByteBuf _buf)
    {
        return new EmitterEffectPackConfig(_buf);
    }

    /// <summary>
    /// 效果包ID
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 效果包名称
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 效果ID列表
    /// </summary>
    public readonly int[] EffectIds;
    public EmitterEffectConfig[] EffectIds_Ref;
    /// <summary>
    /// 描述
    /// </summary>
    public readonly string Desc;
   
    public const int __ID__ = 2042489498;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        EffectIds_Ref = new EmitterEffectConfig[EffectIds.Length];
        for (int _i = 0; _i < EffectIds.Length; _i++) { EffectIds_Ref[_i] = tables.EmitterEffectConfigCategory.GetOrDefault(EffectIds[_i]); }

    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "Name:" + Name + ","
        + "EffectIds:" + Luban.StringUtil.CollectionToString(EffectIds) + ","
        + "Desc:" + Desc + ","
        + "}";
    }
}

}

