
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace ET
{
public partial class EmitterConfigCategory
{
    private readonly System.Collections.Generic.Dictionary<int, EmitterConfig> _dataMap;
    private readonly System.Collections.Generic.List<EmitterConfig> _dataList;
    
    public EmitterConfigCategory(ByteBuf _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, EmitterConfig>();
        _dataList = new System.Collections.Generic.List<EmitterConfig>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            EmitterConfig _v;
            _v = global::ET.EmitterConfig.DeserializeEmitterConfig(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, EmitterConfig> DataMap => _dataMap;
    public System.Collections.Generic.List<EmitterConfig> DataList => _dataList;

    public EmitterConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public EmitterConfig Get(int key) => _dataMap[key];
    public EmitterConfig this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

