
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace ET
{
public sealed partial class MonsterUnitConfig : Luban.BeanBase
{
    public MonsterUnitConfig(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Type = _buf.ReadInt();
        Name = _buf.ReadString();
        Desc = _buf.ReadString();
        MaxHp = _buf.ReadInt();
        Attack = _buf.ReadInt();
        Defense = _buf.ReadInt();
        Speed = _buf.ReadFloat();
        Position = _buf.ReadInt();
        Height = _buf.ReadInt();
        Weight = _buf.ReadInt();
        AI = _buf.ReadInt();
        AI_Ref = null;
        DropId = _buf.ReadInt();
        DropId_Ref = null;
        Exp = _buf.ReadInt();
        Gold = _buf.ReadInt();
    }

    public static MonsterUnitConfig DeserializeMonsterUnitConfig(ByteBuf _buf)
    {
        return new MonsterUnitConfig(_buf);
    }

    /// <summary>
    /// Id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 怪物类型
    /// </summary>
    public readonly int Type;
    /// <summary>
    /// 怪物名称
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 怪物描述
    /// </summary>
    public readonly string Desc;
    /// <summary>
    /// 最大血量
    /// </summary>
    public readonly int MaxHp;
    /// <summary>
    /// 攻击力
    /// </summary>
    public readonly int Attack;
    /// <summary>
    /// 防御力
    /// </summary>
    public readonly int Defense;
    /// <summary>
    /// 移动速度
    /// </summary>
    public readonly float Speed;
    /// <summary>
    /// 位置
    /// </summary>
    public readonly int Position;
    /// <summary>
    /// 身高
    /// </summary>
    public readonly int Height;
    /// <summary>
    /// 体重
    /// </summary>
    public readonly int Weight;
    /// <summary>
    /// AI配置
    /// </summary>
    public readonly int AI;
    public AIConfig AI_Ref;
    /// <summary>
    /// 掉落表ID
    /// </summary>
    public readonly int DropId;
    public ResourceConfig DropId_Ref;
    /// <summary>
    /// 经验值
    /// </summary>
    public readonly int Exp;
    /// <summary>
    /// 金币
    /// </summary>
    public readonly int Gold;
   
    public const int __ID__ = 1823076672;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        AI_Ref = tables.AIConfigCategory.GetOrDefault(AI);
        DropId_Ref = tables.ResourceConfigCategory.GetOrDefault(DropId);
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "Type:" + Type + ","
        + "Name:" + Name + ","
        + "Desc:" + Desc + ","
        + "MaxHp:" + MaxHp + ","
        + "Attack:" + Attack + ","
        + "Defense:" + Defense + ","
        + "Speed:" + Speed + ","
        + "Position:" + Position + ","
        + "Height:" + Height + ","
        + "Weight:" + Weight + ","
        + "AI:" + AI + ","
        + "DropId:" + DropId + ","
        + "Exp:" + Exp + ","
        + "Gold:" + Gold + ","
        + "}";
    }
}

}

