
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace ET
{
public partial struct MonsterSpawnInfo
{
    public MonsterSpawnInfo(ByteBuf _buf) 
    {
        MonsterId = _buf.ReadInt();
        MonsterId_Ref = null;
        Count = _buf.ReadInt();
    }

    public static MonsterSpawnInfo DeserializeMonsterSpawnInfo(ByteBuf _buf)
    {
        return new MonsterSpawnInfo(_buf);
    }

    public readonly int MonsterId;
    public MonsterUnitConfig MonsterId_Ref;
    public readonly int Count;
   

    public  void ResolveRef(Tables tables)
    {
        MonsterId_Ref = tables.MonsterUnitConfigCategory.GetOrDefault(MonsterId);
    }

    public override string ToString()
    {
        return "{ "
        + "MonsterId:" + MonsterId + ","
        + "Count:" + Count + ","
        + "}";
    }
}

}

