
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace ET
{
/// <summary>
/// 资源配置
/// </summary>
public partial class ResourceConfigCategory
{
    private readonly System.Collections.Generic.Dictionary<int, ResourceConfig> _dataMap;
    private readonly System.Collections.Generic.List<ResourceConfig> _dataList;
    
    public ResourceConfigCategory(ByteBuf _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, ResourceConfig>();
        _dataList = new System.Collections.Generic.List<ResourceConfig>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            ResourceConfig _v;
            _v = global::ET.ResourceConfig.DeserializeResourceConfig(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, ResourceConfig> DataMap => _dataMap;
    public System.Collections.Generic.List<ResourceConfig> DataList => _dataList;

    public ResourceConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public ResourceConfig Get(int key) => _dataMap[key];
    public ResourceConfig this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

