
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace ET
{
public partial class SkillEffectConfigCategory
{
    private readonly System.Collections.Generic.Dictionary<int, SkillEffectConfig> _dataMap;
    private readonly System.Collections.Generic.List<SkillEffectConfig> _dataList;
    
    public SkillEffectConfigCategory(ByteBuf _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, SkillEffectConfig>();
        _dataList = new System.Collections.Generic.List<SkillEffectConfig>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            SkillEffectConfig _v;
            _v = global::ET.SkillEffectConfig.DeserializeSkillEffectConfig(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, SkillEffectConfig> DataMap => _dataMap;
    public System.Collections.Generic.List<SkillEffectConfig> DataList => _dataList;

    public SkillEffectConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public SkillEffectConfig Get(int key) => _dataMap[key];
    public SkillEffectConfig this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

