
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace ET
{
public partial class SkillTargetingConfigCategory
{
    private readonly System.Collections.Generic.Dictionary<int, SkillTargetingConfig> _dataMap;
    private readonly System.Collections.Generic.List<SkillTargetingConfig> _dataList;
    
    public SkillTargetingConfigCategory(ByteBuf _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, SkillTargetingConfig>();
        _dataList = new System.Collections.Generic.List<SkillTargetingConfig>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            SkillTargetingConfig _v;
            _v = global::ET.SkillTargetingConfig.DeserializeSkillTargetingConfig(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, SkillTargetingConfig> DataMap => _dataMap;
    public System.Collections.Generic.List<SkillTargetingConfig> DataList => _dataList;

    public SkillTargetingConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public SkillTargetingConfig Get(int key) => _dataMap[key];
    public SkillTargetingConfig this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

