
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace ET
{
public partial class SkillCastCheckConfigCategory
{
    private readonly System.Collections.Generic.Dictionary<int, SkillCastCheckConfig> _dataMap;
    private readonly System.Collections.Generic.List<SkillCastCheckConfig> _dataList;
    
    public SkillCastCheckConfigCategory(ByteBuf _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, SkillCastCheckConfig>();
        _dataList = new System.Collections.Generic.List<SkillCastCheckConfig>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            SkillCastCheckConfig _v;
            _v = global::ET.SkillCastCheckConfig.DeserializeSkillCastCheckConfig(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, SkillCastCheckConfig> DataMap => _dataMap;
    public System.Collections.Generic.List<SkillCastCheckConfig> DataList => _dataList;

    public SkillCastCheckConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public SkillCastCheckConfig Get(int key) => _dataMap[key];
    public SkillCastCheckConfig this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

