
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace ET
{
public sealed partial class SkillEffectConfig : Luban.BeanBase
{
    public SkillEffectConfig(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        EffectType = _buf.ReadInt();
        FormulaType = _buf.ReadInt();
        BaseValue = _buf.ReadFloat();
        RatioAtk = _buf.ReadFloat();
        RatioDef = _buf.ReadFloat();
        MinValue = _buf.ReadInt();
        MaxValue = _buf.ReadInt();
        CanCritical = _buf.ReadBool();
        ApplyTargetFilter = _buf.ReadString();
        Desc = _buf.ReadString();
    }

    public static SkillEffectConfig DeserializeSkillEffectConfig(ByteBuf _buf)
    {
        return new SkillEffectConfig(_buf);
    }

    /// <summary>
    /// 效果ID
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 效果类型
    /// </summary>
    public readonly int EffectType;
    /// <summary>
    /// 公式类型
    /// </summary>
    public readonly int FormulaType;
    /// <summary>
    /// 基础值
    /// </summary>
    public readonly float BaseValue;
    /// <summary>
    /// 攻击系数
    /// </summary>
    public readonly float RatioAtk;
    /// <summary>
    /// 防御系数
    /// </summary>
    public readonly float RatioDef;
    /// <summary>
    /// 最小值
    /// </summary>
    public readonly int MinValue;
    /// <summary>
    /// 最大值
    /// </summary>
    public readonly int MaxValue;
    /// <summary>
    /// 是否可暴击
    /// </summary>
    public readonly bool CanCritical;
    /// <summary>
    /// 目标过滤扩展
    /// </summary>
    public readonly string ApplyTargetFilter;
    /// <summary>
    /// 描述
    /// </summary>
    public readonly string Desc;
   
    public const int __ID__ = 170943748;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "EffectType:" + EffectType + ","
        + "FormulaType:" + FormulaType + ","
        + "BaseValue:" + BaseValue + ","
        + "RatioAtk:" + RatioAtk + ","
        + "RatioDef:" + RatioDef + ","
        + "MinValue:" + MinValue + ","
        + "MaxValue:" + MaxValue + ","
        + "CanCritical:" + CanCritical + ","
        + "ApplyTargetFilter:" + ApplyTargetFilter + ","
        + "Desc:" + Desc + ","
        + "}";
    }
}

}

