
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace ET
{
public sealed partial class SkillConfig : Luban.BeanBase
{
    public SkillConfig(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Code = _buf.ReadString();
        Name = _buf.ReadString();
        SkillKind = _buf.ReadInt();
        CastType = _buf.ReadInt();
        TargetType = _buf.ReadInt();
        TargetingConfigId = _buf.ReadInt();
        TargetingConfigId_Ref = null;
        CastCheckConfigId = _buf.ReadInt();
        CastCheckConfigId_Ref = null;
        CooldownGroupId = _buf.ReadInt();
        CooldownMs = _buf.ReadInt();
        Priority = _buf.ReadInt();
        CanMoveCast = _buf.ReadBool();
        NeedExplicitTarget = _buf.ReadBool();
        EffectGroupId = _buf.ReadInt();
        EffectGroupId_Ref = null;
        IsEnabled = _buf.ReadBool();
        Desc = _buf.ReadString();
    }

    public static SkillConfig DeserializeSkillConfig(ByteBuf _buf)
    {
        return new SkillConfig(_buf);
    }

    /// <summary>
    /// 技能ID
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 技能代码名
    /// </summary>
    public readonly string Code;
    /// <summary>
    /// 技能名称
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 技能类型
    /// </summary>
    public readonly int SkillKind;
    /// <summary>
    /// 施法类型
    /// </summary>
    public readonly int CastType;
    /// <summary>
    /// 目标类型
    /// </summary>
    public readonly int TargetType;
    /// <summary>
    /// 目标配置ID
    /// </summary>
    public readonly int TargetingConfigId;
    public SkillTargetingConfig TargetingConfigId_Ref;
    /// <summary>
    /// 施法校验配置ID
    /// </summary>
    public readonly int CastCheckConfigId;
    public SkillCastCheckConfig CastCheckConfigId_Ref;
    /// <summary>
    /// 冷却组ID
    /// </summary>
    public readonly int CooldownGroupId;
    /// <summary>
    /// 冷却毫秒
    /// </summary>
    public readonly int CooldownMs;
    /// <summary>
    /// 优先级
    /// </summary>
    public readonly int Priority;
    /// <summary>
    /// 是否可移动施法
    /// </summary>
    public readonly bool CanMoveCast;
    /// <summary>
    /// 是否必须显式指定目标
    /// </summary>
    public readonly bool NeedExplicitTarget;
    /// <summary>
    /// 效果组ID
    /// </summary>
    public readonly int EffectGroupId;
    public SkillEffectGroupConfig EffectGroupId_Ref;
    /// <summary>
    /// 是否启用
    /// </summary>
    public readonly bool IsEnabled;
    /// <summary>
    /// 描述
    /// </summary>
    public readonly string Desc;
   
    public const int __ID__ = -844226349;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        TargetingConfigId_Ref = tables.SkillTargetingConfigCategory.GetOrDefault(TargetingConfigId);
        CastCheckConfigId_Ref = tables.SkillCastCheckConfigCategory.GetOrDefault(CastCheckConfigId);
        EffectGroupId_Ref = tables.SkillEffectGroupConfigCategory.GetOrDefault(EffectGroupId);
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "Code:" + Code + ","
        + "Name:" + Name + ","
        + "SkillKind:" + SkillKind + ","
        + "CastType:" + CastType + ","
        + "TargetType:" + TargetType + ","
        + "TargetingConfigId:" + TargetingConfigId + ","
        + "CastCheckConfigId:" + CastCheckConfigId + ","
        + "CooldownGroupId:" + CooldownGroupId + ","
        + "CooldownMs:" + CooldownMs + ","
        + "Priority:" + Priority + ","
        + "CanMoveCast:" + CanMoveCast + ","
        + "NeedExplicitTarget:" + NeedExplicitTarget + ","
        + "EffectGroupId:" + EffectGroupId + ","
        + "IsEnabled:" + IsEnabled + ","
        + "Desc:" + Desc + ","
        + "}";
    }
}

}

