
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace ET
{
public partial class SkillEffectGroupConfigCategory
{
    private readonly System.Collections.Generic.Dictionary<int, SkillEffectGroupConfig> _dataMap;
    private readonly System.Collections.Generic.List<SkillEffectGroupConfig> _dataList;
    
    public SkillEffectGroupConfigCategory(ByteBuf _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, SkillEffectGroupConfig>();
        _dataList = new System.Collections.Generic.List<SkillEffectGroupConfig>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            SkillEffectGroupConfig _v;
            _v = global::ET.SkillEffectGroupConfig.DeserializeSkillEffectGroupConfig(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, SkillEffectGroupConfig> DataMap => _dataMap;
    public System.Collections.Generic.List<SkillEffectGroupConfig> DataList => _dataList;

    public SkillEffectGroupConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public SkillEffectGroupConfig Get(int key) => _dataMap[key];
    public SkillEffectGroupConfig this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

