
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace ET
{
public partial class SkillConfigCategory
{
    private readonly System.Collections.Generic.Dictionary<int, SkillConfig> _dataMap;
    private readonly System.Collections.Generic.List<SkillConfig> _dataList;
    
    public SkillConfigCategory(ByteBuf _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, SkillConfig>();
        _dataList = new System.Collections.Generic.List<SkillConfig>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            SkillConfig _v;
            _v = global::ET.SkillConfig.DeserializeSkillConfig(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, SkillConfig> DataMap => _dataMap;
    public System.Collections.Generic.List<SkillConfig> DataList => _dataList;

    public SkillConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public SkillConfig Get(int key) => _dataMap[key];
    public SkillConfig this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

