
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace ET
{
public partial class SpawnConfigCategory
{
    private readonly System.Collections.Generic.Dictionary<int, SpawnConfig> _dataMap;
    private readonly System.Collections.Generic.List<SpawnConfig> _dataList;
    
    public SpawnConfigCategory(ByteBuf _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, SpawnConfig>();
        _dataList = new System.Collections.Generic.List<SpawnConfig>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            SpawnConfig _v;
            _v = global::ET.SpawnConfig.DeserializeSpawnConfig(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, SpawnConfig> DataMap => _dataMap;
    public System.Collections.Generic.List<SpawnConfig> DataList => _dataList;

    public SpawnConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public SpawnConfig Get(int key) => _dataMap[key];
    public SpawnConfig this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

