
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace ET
{
public sealed partial class SpawnConfig : Luban.BeanBase
{
    public SpawnConfig(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        PositionX = _buf.ReadFloat();
        PositionZ = _buf.ReadFloat();
        SpreadRange = _buf.ReadFloat();
        {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);Monsters = new System.Collections.Generic.List<MonsterSpawnInfo>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { MonsterSpawnInfo _e0;  _e0 = global::ET.MonsterSpawnInfo.DeserializeMonsterSpawnInfo(_buf); Monsters.Add(_e0);}}
        Desc = _buf.ReadString();
    }

    public static SpawnConfig DeserializeSpawnConfig(ByteBuf _buf)
    {
        return new SpawnConfig(_buf);
    }

    /// <summary>
    /// Id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// PositionX
    /// </summary>
    public readonly float PositionX;
    /// <summary>
    /// PositionZ
    /// </summary>
    public readonly float PositionZ;
    /// <summary>
    /// SpreadRange
    /// </summary>
    public readonly float SpreadRange;
    /// <summary>
    /// Monsters
    /// </summary>
    public readonly System.Collections.Generic.List<MonsterSpawnInfo> Monsters;
    /// <summary>
    /// Desc
    /// </summary>
    public readonly string Desc;
   
    public const int __ID__ = -780975491;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "PositionX:" + PositionX + ","
        + "PositionZ:" + PositionZ + ","
        + "SpreadRange:" + SpreadRange + ","
        + "Monsters:" + Luban.StringUtil.CollectionToString(Monsters) + ","
        + "Desc:" + Desc + ","
        + "}";
    }
}

}

