
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace ET
{
public partial class StageConfigCategory
{
    private readonly System.Collections.Generic.Dictionary<int, StageConfig> _dataMap;
    private readonly System.Collections.Generic.List<StageConfig> _dataList;
    
    public StageConfigCategory(ByteBuf _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, StageConfig>();
        _dataList = new System.Collections.Generic.List<StageConfig>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            StageConfig _v;
            _v = global::ET.StageConfig.DeserializeStageConfig(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, StageConfig> DataMap => _dataMap;
    public System.Collections.Generic.List<StageConfig> DataList => _dataList;

    public StageConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public StageConfig Get(int key) => _dataMap[key];
    public StageConfig this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

