
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace ET
{
public partial class Tables
{
    public AIConfigCategory AIConfigCategory {get; }
    public UnitConfigCategory UnitConfigCategory {get; }
    /// <summary>
    /// 资源配置
    /// </summary>
    public ResourceConfigCategory ResourceConfigCategory {get; }

    public Tables(System.Func<string, ByteBuf> loader)
    {
        AIConfigCategory = new AIConfigCategory(loader("AIConfigCategory"));
        UnitConfigCategory = new UnitConfigCategory(loader("UnitConfigCategory"));
        ResourceConfigCategory = new ResourceConfigCategory(loader("ResourceConfigCategory"));
        ResolveRef();
    }
    
    private void ResolveRef()
    {
        AIConfigCategory.ResolveRef(this);
        UnitConfigCategory.ResolveRef(this);
        ResourceConfigCategory.ResolveRef(this);
    }
}

}
