
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace ET
{
public partial class Tables
{
    public AIConfigCategory AIConfigCategory {get; }
    public UnitConfigCategory UnitConfigCategory {get; }
    /// <summary>
    /// 资源配置
    /// </summary>
    public ResourceConfigCategory ResourceConfigCategory {get; }
    public MonsterUnitConfigCategory MonsterUnitConfigCategory {get; }
    public SpawnConfigCategory SpawnConfigCategory {get; }
    public StageConfigCategory StageConfigCategory {get; }
    public WaveConfigCategory WaveConfigCategory {get; }
    public UnitCombatConfigCategory UnitCombatConfigCategory {get; }
    /// <summary>
    /// 发射器升级配置
    /// </summary>
    public EmitterUpgradeConfigCategory EmitterUpgradeConfigCategory {get; }
    public EmitterConfigCategory EmitterConfigCategory {get; }
    public SkillTargetingConfigCategory SkillTargetingConfigCategory {get; }
    public BuffGroupConfigCategory BuffGroupConfigCategory {get; }
    public BuffConfigCategory BuffConfigCategory {get; }
    public BattleGlobalConfigCategory BattleGlobalConfigCategory {get; }
    /// <summary>
    /// 发射器效果配置
    /// </summary>
    public EmitterEffectConfigCategory EmitterEffectConfigCategory {get; }
    /// <summary>
    /// 发射器效果包配置
    /// </summary>
    public EmitterEffectPackConfigCategory EmitterEffectPackConfigCategory {get; }

    public Tables(System.Func<string, ByteBuf> loader)
    {
        AIConfigCategory = new AIConfigCategory(loader("AIConfigCategory"));
        UnitConfigCategory = new UnitConfigCategory(loader("UnitConfigCategory"));
        ResourceConfigCategory = new ResourceConfigCategory(loader("ResourceConfigCategory"));
        MonsterUnitConfigCategory = new MonsterUnitConfigCategory(loader("MonsterUnitConfigCategory"));
        SpawnConfigCategory = new SpawnConfigCategory(loader("SpawnConfigCategory"));
        StageConfigCategory = new StageConfigCategory(loader("StageConfigCategory"));
        WaveConfigCategory = new WaveConfigCategory(loader("WaveConfigCategory"));
        UnitCombatConfigCategory = new UnitCombatConfigCategory(loader("UnitCombatConfigCategory"));
        EmitterUpgradeConfigCategory = new EmitterUpgradeConfigCategory(loader("EmitterUpgradeConfigCategory"));
        EmitterConfigCategory = new EmitterConfigCategory(loader("EmitterConfigCategory"));
        SkillTargetingConfigCategory = new SkillTargetingConfigCategory(loader("SkillTargetingConfigCategory"));
        BuffGroupConfigCategory = new BuffGroupConfigCategory(loader("BuffGroupConfigCategory"));
        BuffConfigCategory = new BuffConfigCategory(loader("BuffConfigCategory"));
        BattleGlobalConfigCategory = new BattleGlobalConfigCategory(loader("BattleGlobalConfigCategory"));
        EmitterEffectConfigCategory = new EmitterEffectConfigCategory(loader("EmitterEffectConfigCategory"));
        EmitterEffectPackConfigCategory = new EmitterEffectPackConfigCategory(loader("EmitterEffectPackConfigCategory"));
        ResolveRef();
    }
    
    private void ResolveRef()
    {
        AIConfigCategory.ResolveRef(this);
        UnitConfigCategory.ResolveRef(this);
        ResourceConfigCategory.ResolveRef(this);
        MonsterUnitConfigCategory.ResolveRef(this);
        SpawnConfigCategory.ResolveRef(this);
        StageConfigCategory.ResolveRef(this);
        WaveConfigCategory.ResolveRef(this);
        UnitCombatConfigCategory.ResolveRef(this);
        EmitterUpgradeConfigCategory.ResolveRef(this);
        EmitterConfigCategory.ResolveRef(this);
        SkillTargetingConfigCategory.ResolveRef(this);
        BuffGroupConfigCategory.ResolveRef(this);
        BuffConfigCategory.ResolveRef(this);
        EmitterEffectConfigCategory.ResolveRef(this);
        EmitterEffectPackConfigCategory.ResolveRef(this);
    }
}

}

