
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace ET
{
public sealed partial class UnitCombatConfig : Luban.BeanBase
{
    public UnitCombatConfig(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        ConfigId = _buf.ReadInt();
        NormalAttackSkillId = _buf.ReadInt();
        NormalAttackSkillId_Ref = null;
        {int __n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);AutoSkillIds = new int[__n0];for(var __index0 = 0 ; __index0 < __n0 ; __index0++) { int __e0;__e0 = _buf.ReadInt(); AutoSkillIds[__index0] = __e0;}}
        MoveSpeed = _buf.ReadFloat();
        AutoCastNormalAttack = _buf.ReadBool();
        DefaultTargetPolicy = _buf.ReadString();
        Desc = _buf.ReadString();
    }

    public static UnitCombatConfig DeserializeUnitCombatConfig(ByteBuf _buf)
    {
        return new UnitCombatConfig(_buf);
    }

    /// <summary>
    /// 主键
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 战斗单位配置ID（可对应UnitConfig或MonsterUnitConfig）
    /// </summary>
    public readonly int ConfigId;
    /// <summary>
    /// 默认普攻技能ID
    /// </summary>
    public readonly int NormalAttackSkillId;
    public SkillConfig NormalAttackSkillId_Ref;
    /// <summary>
    /// AI自动择优技能列表（为空则回退普攻）
    /// </summary>
    public readonly int[] AutoSkillIds;
    /// <summary>
    /// 移动速度（米/秒）
    /// </summary>
    public readonly float MoveSpeed;
    /// <summary>
    /// 是否自动释放普攻
    /// </summary>
    public readonly bool AutoCastNormalAttack;
    /// <summary>
    /// 默认目标策略
    /// </summary>
    public readonly string DefaultTargetPolicy;
    /// <summary>
    /// 描述
    /// </summary>
    public readonly string Desc;
   
    public const int __ID__ = 1584771866;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        NormalAttackSkillId_Ref = tables.SkillConfigCategory.GetOrDefault(NormalAttackSkillId);
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "ConfigId:" + ConfigId + ","
        + "NormalAttackSkillId:" + NormalAttackSkillId + ","
        + "AutoSkillIds:" + Luban.StringUtil.CollectionToString(AutoSkillIds) + ","
        + "MoveSpeed:" + MoveSpeed + ","
        + "AutoCastNormalAttack:" + AutoCastNormalAttack + ","
        + "DefaultTargetPolicy:" + DefaultTargetPolicy + ","
        + "Desc:" + Desc + ","
        + "}";
    }
}

}

