
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace ET
{
public sealed partial class WaveConfig : Luban.BeanBase
{
    public WaveConfig(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        WaveNumber = _buf.ReadInt();
        {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);Batches = new System.Collections.Generic.List<BatchInfo>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { BatchInfo _e0;  _e0 = global::ET.BatchInfo.DeserializeBatchInfo(_buf); Batches.Add(_e0);}}
        WaveInterval = _buf.ReadInt();
        Desc = _buf.ReadString();
    }

    public static WaveConfig DeserializeWaveConfig(ByteBuf _buf)
    {
        return new WaveConfig(_buf);
    }

    /// <summary>
    /// Id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// WaveNumber
    /// </summary>
    public readonly int WaveNumber;
    /// <summary>
    /// Batches
    /// </summary>
    public readonly System.Collections.Generic.List<BatchInfo> Batches;
    /// <summary>
    /// WaveInterval
    /// </summary>
    public readonly int WaveInterval;
    /// <summary>
    /// Desc
    /// </summary>
    public readonly string Desc;
   
    public const int __ID__ = 1814560699;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "WaveNumber:" + WaveNumber + ","
        + "Batches:" + Luban.StringUtil.CollectionToString(Batches) + ","
        + "WaveInterval:" + WaveInterval + ","
        + "Desc:" + Desc + ","
        + "}";
    }
}

}

