
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace ET
{
public partial class WaveConfigCategory
{
    private readonly System.Collections.Generic.Dictionary<int, WaveConfig> _dataMap;
    private readonly System.Collections.Generic.List<WaveConfig> _dataList;
    
    public WaveConfigCategory(ByteBuf _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, WaveConfig>();
        _dataList = new System.Collections.Generic.List<WaveConfig>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            WaveConfig _v;
            _v = global::ET.WaveConfig.DeserializeWaveConfig(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, WaveConfig> DataMap => _dataMap;
    public System.Collections.Generic.List<WaveConfig> DataList => _dataList;

    public WaveConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public WaveConfig Get(int key) => _dataMap[key];
    public WaveConfig this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

