
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace ET
{
    [EnableClass]
    public sealed partial class AutoBattleStrategyConfig : BeanBase
    {
        public AutoBattleStrategyConfig(ByteBuf _buf)
        {
            Id = _buf.ReadInt();
            Code = _buf.ReadString();
            SkillSelectRule = _buf.ReadInt();
            TargetSelectRule = _buf.ReadInt();
            PreferBoss = _buf.ReadBool();
            PreferElite = _buf.ReadBool();
            PreferCurrentTarget = _buf.ReadBool();
            AllowPreMoveOnCooldown = _buf.ReadBool();
            TargetSwitchTolerance = _buf.ReadFloat();
            Desc = _buf.ReadString();

            PostInit();
        }

        public static AutoBattleStrategyConfig DeserializeAutoBattleStrategyConfig(ByteBuf _buf)
        {
            return new AutoBattleStrategyConfig(_buf);
        }

        /// <summary>
        /// 主键
        /// </summary>
        public readonly int Id;

        /// <summary>
        /// 策略代码
        /// </summary>
        public readonly string Code;

        /// <summary>
        /// 技能选择规则
        /// </summary>
        public readonly int SkillSelectRule;

        /// <summary>
        /// 目标选择规则
        /// </summary>
        public readonly int TargetSelectRule;

        /// <summary>
        /// 是否优先Boss
        /// </summary>
        public readonly bool PreferBoss;

        /// <summary>
        /// 是否优先精英
        /// </summary>
        public readonly bool PreferElite;

        /// <summary>
        /// 是否优先保持当前目标
        /// </summary>
        public readonly bool PreferCurrentTarget;

        /// <summary>
        /// 是否允许为冷却中技能预走位
        /// </summary>
        public readonly bool AllowPreMoveOnCooldown;

        /// <summary>
        /// 切换目标容差距离
        /// </summary>
        public readonly float TargetSwitchTolerance;

        /// <summary>
        /// 描述
        /// </summary>
        public readonly string Desc;

        public const int __ID__ = -858623012;

        public override int GetTypeId() => __ID__;

        public override string ToString()
        {
            return "{ "
            + "Id:" + Id + ","
            + "Code:" + Code + ","
            + "SkillSelectRule:" + SkillSelectRule + ","
            + "TargetSelectRule:" + TargetSelectRule + ","
            + "PreferBoss:" + PreferBoss + ","
            + "PreferElite:" + PreferElite + ","
            + "PreferCurrentTarget:" + PreferCurrentTarget + ","
            + "AllowPreMoveOnCooldown:" + AllowPreMoveOnCooldown + ","
            + "TargetSwitchTolerance:" + TargetSwitchTolerance + ","
            + "Desc:" + Desc + ","
            + "}";
        }

        partial void PostInit();
    }
}
