
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Collections.Generic;

namespace ET
{
    /// <summary>
    /// 自动战斗策略配置
    /// </summary>
    [Config]
    public partial class AutoBattleStrategyConfigCategory : Singleton<AutoBattleStrategyConfigCategory>
    {
        private readonly Dictionary<int, AutoBattleStrategyConfig> _dataMap;
        private readonly List<AutoBattleStrategyConfig> _dataList;

        public AutoBattleStrategyConfigCategory(ByteBuf _buf)
        {
            _dataMap = new Dictionary<int, AutoBattleStrategyConfig>();
            _dataList = new List<AutoBattleStrategyConfig>();

            for (int n = _buf.ReadSize(); n > 0; --n)
            {
                AutoBattleStrategyConfig _v;
                _v = global::ET.AutoBattleStrategyConfig.DeserializeAutoBattleStrategyConfig(_buf);
                _dataList.Add(_v);
                _dataMap.Add(_v.Id, _v);
            }

            PostInit();
        }

        public Dictionary<int, AutoBattleStrategyConfig> DataMap => _dataMap;
        public List<AutoBattleStrategyConfig> DataList => _dataList;

        public AutoBattleStrategyConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
        public AutoBattleStrategyConfig Get(int key) => _dataMap[key];
        public AutoBattleStrategyConfig this[int key] => _dataMap[key];

        partial void PostInit();
    }
}
