
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace ET
{
    public partial struct BatchInfo
    {
        public BatchInfo(ByteBuf _buf)
        {
            SpawnId = _buf.ReadInt();
            Delay = _buf.ReadInt();

            PostInit();
        }

        public static BatchInfo DeserializeBatchInfo(ByteBuf _buf)
        {
            return new BatchInfo(_buf);
        }

        public readonly int SpawnId;

        public readonly int Delay;

        public override string ToString()
        {
            return "{ "
            + "SpawnId:" + SpawnId + ","
            + "Delay:" + Delay + ","
            + "}";
        }

        partial void PostInit();
    }
}
