
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace ET
{
    [EnableClass]
    public sealed partial class BattleGlobalConfig : BeanBase
    {
        public BattleGlobalConfig(ByteBuf _buf)
        {
            SlotSpacing = _buf.ReadFloat();
            Description = _buf.ReadString();

            PostInit();
        }

        public static BattleGlobalConfig DeserializeBattleGlobalConfig(ByteBuf _buf)
        {
            return new BattleGlobalConfig(_buf);
        }

        /// <summary>
        /// SlotSpacing
        /// </summary>
        public readonly float SlotSpacing;

        /// <summary>
        /// Description
        /// </summary>
        public readonly string Description;

        public const int __ID__ = 1436744125;

        public override int GetTypeId() => __ID__;

        public override string ToString()
        {
            return "{ "
            + "SlotSpacing:" + SlotSpacing + ","
            + "Description:" + Description + ","
            + "}";
        }

        partial void PostInit();
    }
}
