
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace ET
{
    [EnableClass]
    public sealed partial class BuffConfig : BeanBase
    {
        public BuffConfig(ByteBuf _buf)
        {
            Id = _buf.ReadInt();
            EffectType = _buf.ReadInt();
            FormulaType = _buf.ReadInt();
            BaseValue = _buf.ReadFloat();
            RatioAtk = _buf.ReadFloat();
            RatioDef = _buf.ReadFloat();
            MinValue = _buf.ReadInt();
            MaxValue = _buf.ReadInt();
            CanCritical = _buf.ReadBool();
            ApplyTargetFilter = _buf.ReadString();
            Desc = _buf.ReadString();

            PostInit();
        }

        public static BuffConfig DeserializeBuffConfig(ByteBuf _buf)
        {
            return new BuffConfig(_buf);
        }

        /// <summary>
        /// 效果ID
        /// </summary>
        public readonly int Id;

        /// <summary>
        /// 效果类型
        /// </summary>
        public readonly int EffectType;

        /// <summary>
        /// 公式类型
        /// </summary>
        public readonly int FormulaType;

        /// <summary>
        /// 基础值
        /// </summary>
        public readonly float BaseValue;

        /// <summary>
        /// 攻击系数
        /// </summary>
        public readonly float RatioAtk;

        /// <summary>
        /// 防御系数
        /// </summary>
        public readonly float RatioDef;

        /// <summary>
        /// 最小值
        /// </summary>
        public readonly int MinValue;

        /// <summary>
        /// 最大值
        /// </summary>
        public readonly int MaxValue;

        /// <summary>
        /// 是否可暴击
        /// </summary>
        public readonly bool CanCritical;

        /// <summary>
        /// 目标过滤扩展
        /// </summary>
        public readonly string ApplyTargetFilter;

        /// <summary>
        /// 描述
        /// </summary>
        public readonly string Desc;

        public const int __ID__ = -1370631787;

        public override int GetTypeId() => __ID__;

        public override string ToString()
        {
            return "{ "
            + "Id:" + Id + ","
            + "EffectType:" + EffectType + ","
            + "FormulaType:" + FormulaType + ","
            + "BaseValue:" + BaseValue + ","
            + "RatioAtk:" + RatioAtk + ","
            + "RatioDef:" + RatioDef + ","
            + "MinValue:" + MinValue + ","
            + "MaxValue:" + MaxValue + ","
            + "CanCritical:" + CanCritical + ","
            + "ApplyTargetFilter:" + ApplyTargetFilter + ","
            + "Desc:" + Desc + ","
            + "}";
        }

        partial void PostInit();
    }
}
