
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace ET
{
    [EnableClass]
    public sealed partial class BuffGroupConfig : BeanBase
    {
        public BuffGroupConfig(ByteBuf _buf)
        {
            Id = _buf.ReadInt();
            {int __n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);BuffIds = new int[__n0];for(var __index0 = 0 ; __index0 < __n0 ; __index0++) { int __e0;__e0 = _buf.ReadInt(); BuffIds[__index0] = __e0;}}
            ExecMode = _buf.ReadInt();
            Desc = _buf.ReadString();

            PostInit();
        }

        public static BuffGroupConfig DeserializeBuffGroupConfig(ByteBuf _buf)
        {
            return new BuffGroupConfig(_buf);
        }

        /// <summary>
        /// Buff组ID
        /// </summary>
        public readonly int Id;

        /// <summary>
        /// BuffID列表
        /// </summary>
        public readonly int[] BuffIds;

        /// <summary>
        /// 执行方式
        /// </summary>
        public readonly int ExecMode;

        /// <summary>
        /// 描述
        /// </summary>
        public readonly string Desc;

        public const int __ID__ = -218040274;

        public override int GetTypeId() => __ID__;

        public override string ToString()
        {
            return "{ "
            + "Id:" + Id + ","
            + "BuffIds:" + Luban.StringUtil.CollectionToString(BuffIds) + ","
            + "ExecMode:" + ExecMode + ","
            + "Desc:" + Desc + ","
            + "}";
        }

        partial void PostInit();
    }
}
