
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Collections.Generic;

namespace ET
{
    [Config]
    public partial class BuffGroupConfigCategory : Singleton<BuffGroupConfigCategory>
    {
        private readonly Dictionary<int, BuffGroupConfig> _dataMap;
        private readonly List<BuffGroupConfig> _dataList;

        public BuffGroupConfigCategory(ByteBuf _buf)
        {
            _dataMap = new Dictionary<int, BuffGroupConfig>();
            _dataList = new List<BuffGroupConfig>();

            for (int n = _buf.ReadSize(); n > 0; --n)
            {
                BuffGroupConfig _v;
                _v = global::ET.BuffGroupConfig.DeserializeBuffGroupConfig(_buf);
                _dataList.Add(_v);
                _dataMap.Add(_v.Id, _v);
            }

            PostInit();
        }

        public Dictionary<int, BuffGroupConfig> DataMap => _dataMap;
        public List<BuffGroupConfig> DataList => _dataList;

        public BuffGroupConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
        public BuffGroupConfig Get(int key) => _dataMap[key];
        public BuffGroupConfig this[int key] => _dataMap[key];

        partial void PostInit();
    }
}
