
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Collections.Generic;

namespace ET
{
    /// <summary>
    /// 发射器效果配置
    /// </summary>
    [Config]
    public partial class EmitterEffectConfigCategory : Singleton<EmitterEffectConfigCategory>
    {
        private readonly Dictionary<int, EmitterEffectConfig> _dataMap;
        private readonly List<EmitterEffectConfig> _dataList;

        public EmitterEffectConfigCategory(ByteBuf _buf)
        {
            _dataMap = new Dictionary<int, EmitterEffectConfig>();
            _dataList = new List<EmitterEffectConfig>();

            for (int n = _buf.ReadSize(); n > 0; --n)
            {
                EmitterEffectConfig _v;
                _v = global::ET.EmitterEffectConfig.DeserializeEmitterEffectConfig(_buf);
                _dataList.Add(_v);
                _dataMap.Add(_v.Id, _v);
            }

            PostInit();
        }

        public Dictionary<int, EmitterEffectConfig> DataMap => _dataMap;
        public List<EmitterEffectConfig> DataList => _dataList;

        public EmitterEffectConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
        public EmitterEffectConfig Get(int key) => _dataMap[key];
        public EmitterEffectConfig this[int key] => _dataMap[key];

        partial void PostInit();
    }
}

