
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Collections.Generic;

namespace ET
{
    [Config]
    public partial class EmitterConfigCategory : Singleton<EmitterConfigCategory>
    {
        private readonly Dictionary<int, EmitterConfig> _dataMap;
        private readonly List<EmitterConfig> _dataList;

        public EmitterConfigCategory(ByteBuf _buf)
        {
            _dataMap = new Dictionary<int, EmitterConfig>();
            _dataList = new List<EmitterConfig>();

            for (int n = _buf.ReadSize(); n > 0; --n)
            {
                EmitterConfig _v;
                _v = global::ET.EmitterConfig.DeserializeEmitterConfig(_buf);
                _dataList.Add(_v);
                _dataMap.Add(_v.Id, _v);
            }

            PostInit();
        }

        public Dictionary<int, EmitterConfig> DataMap => _dataMap;
        public List<EmitterConfig> DataList => _dataList;

        public EmitterConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
        public EmitterConfig Get(int key) => _dataMap[key];
        public EmitterConfig this[int key] => _dataMap[key];

        partial void PostInit();
    }
}
