
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace ET
{
    [EnableClass]
    public sealed partial class EmitterUpgradeConfig : BeanBase
    {
        public EmitterUpgradeConfig(ByteBuf _buf)
        {
            Id = _buf.ReadInt();
            UpgradeConfigId = _buf.ReadInt();
            Level = _buf.ReadInt();
            Code = _buf.ReadString();
            Name = _buf.ReadString();
            CooldownMs = _buf.ReadInt();
            Range = _buf.ReadFloat();
            BaseDamage = _buf.ReadFloat();
            AttackRatio = _buf.ReadFloat();
            Desc = _buf.ReadString();

            PostInit();
        }

        public static EmitterUpgradeConfig DeserializeEmitterUpgradeConfig(ByteBuf _buf)
        {
            return new EmitterUpgradeConfig(_buf);
        }

        /// <summary>
        /// 升级等级配置ID
        /// </summary>
        public readonly int Id;

        /// <summary>
        /// 升级方案ID
        /// </summary>
        public readonly int UpgradeConfigId;

        /// <summary>
        /// 等级
        /// </summary>
        public readonly int Level;

        /// <summary>
        /// 代码名
        /// </summary>
        public readonly string Code;

        /// <summary>
        /// 名称
        /// </summary>
        public readonly string Name;

        /// <summary>
        /// 最终冷却毫秒
        /// </summary>
        public readonly int CooldownMs;

        /// <summary>
        /// 最终攻击射程
        /// </summary>
        public readonly float Range;

        /// <summary>
        /// 最终基础伤害
        /// </summary>
        public readonly float BaseDamage;

        /// <summary>
        /// 最终攻击力系数
        /// </summary>
        public readonly float AttackRatio;

        /// <summary>
        /// 描述
        /// </summary>
        public readonly string Desc;

        public const int __ID__ = -994758704;

        public override int GetTypeId() => __ID__;

        public override string ToString()
        {
            return "{ "
            + "Id:" + Id + ","
            + "UpgradeConfigId:" + UpgradeConfigId + ","
            + "Level:" + Level + ","
            + "Code:" + Code + ","
            + "Name:" + Name + ","
            + "CooldownMs:" + CooldownMs + ","
            + "Range:" + Range + ","
            + "BaseDamage:" + BaseDamage + ","
            + "AttackRatio:" + AttackRatio + ","
            + "Desc:" + Desc + ","
            + "}";
        }

        partial void PostInit();
    }
}
