
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Collections.Generic;

namespace ET
{
    /// <summary>
    /// 发射器升级配置
    /// </summary>
    [Config]
    public partial class EmitterUpgradeConfigCategory : Singleton<EmitterUpgradeConfigCategory>
    {
        private readonly Dictionary<int, EmitterUpgradeConfig> _dataMap;
        private readonly List<EmitterUpgradeConfig> _dataList;

        public EmitterUpgradeConfigCategory(ByteBuf _buf)
        {
            _dataMap = new Dictionary<int, EmitterUpgradeConfig>();
            _dataList = new List<EmitterUpgradeConfig>();

            for (int n = _buf.ReadSize(); n > 0; --n)
            {
                EmitterUpgradeConfig _v;
                _v = global::ET.EmitterUpgradeConfig.DeserializeEmitterUpgradeConfig(_buf);
                _dataList.Add(_v);
                _dataMap.Add(_v.Id, _v);
            }

            PostInit();
        }

        public Dictionary<int, EmitterUpgradeConfig> DataMap => _dataMap;
        public List<EmitterUpgradeConfig> DataList => _dataList;

        public EmitterUpgradeConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
        public EmitterUpgradeConfig Get(int key) => _dataMap[key];
        public EmitterUpgradeConfig this[int key] => _dataMap[key];

        partial void PostInit();
    }
}
