
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Collections.Generic;

namespace ET
{
    [Config]
    public partial class MonsterUnitConfigCategory : Singleton<MonsterUnitConfigCategory>
    {
        private readonly Dictionary<int, MonsterUnitConfig> _dataMap;
        private readonly List<MonsterUnitConfig> _dataList;

        public MonsterUnitConfigCategory(ByteBuf _buf)
        {
            _dataMap = new Dictionary<int, MonsterUnitConfig>();
            _dataList = new List<MonsterUnitConfig>();

            for (int n = _buf.ReadSize(); n > 0; --n)
            {
                MonsterUnitConfig _v;
                _v = global::ET.MonsterUnitConfig.DeserializeMonsterUnitConfig(_buf);
                _dataList.Add(_v);
                _dataMap.Add(_v.Id, _v);
            }

            PostInit();
        }

        public Dictionary<int, MonsterUnitConfig> DataMap => _dataMap;
        public List<MonsterUnitConfig> DataList => _dataList;

        public MonsterUnitConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
        public MonsterUnitConfig Get(int key) => _dataMap[key];
        public MonsterUnitConfig this[int key] => _dataMap[key];

        partial void PostInit();
    }
}

