
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace ET
{
    public partial struct MonsterSpawnInfo
    {
        public MonsterSpawnInfo(ByteBuf _buf)
        {
            MonsterId = _buf.ReadInt();
            Count = _buf.ReadInt();

            PostInit();
        }

        public static MonsterSpawnInfo DeserializeMonsterSpawnInfo(ByteBuf _buf)
        {
            return new MonsterSpawnInfo(_buf);
        }

        public readonly int MonsterId;

        public readonly int Count;

        public override string ToString()
        {
            return "{ "
            + "MonsterId:" + MonsterId + ","
            + "Count:" + Count + ","
            + "}";
        }

        partial void PostInit();
    }
}
