
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Collections.Generic;

namespace ET
{
    [Config]
    public partial class SkillEffectGroupConfigCategory : Singleton<SkillEffectGroupConfigCategory>
    {
        private readonly Dictionary<int, SkillEffectGroupConfig> _dataMap;
        private readonly List<SkillEffectGroupConfig> _dataList;

        public SkillEffectGroupConfigCategory(ByteBuf _buf)
        {
            _dataMap = new Dictionary<int, SkillEffectGroupConfig>();
            _dataList = new List<SkillEffectGroupConfig>();

            for (int n = _buf.ReadSize(); n > 0; --n)
            {
                SkillEffectGroupConfig _v;
                _v = global::ET.SkillEffectGroupConfig.DeserializeSkillEffectGroupConfig(_buf);
                _dataList.Add(_v);
                _dataMap.Add(_v.Id, _v);
            }

            PostInit();
        }

        public Dictionary<int, SkillEffectGroupConfig> DataMap => _dataMap;
        public List<SkillEffectGroupConfig> DataList => _dataList;

        public SkillEffectGroupConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
        public SkillEffectGroupConfig Get(int key) => _dataMap[key];
        public SkillEffectGroupConfig this[int key] => _dataMap[key];

        partial void PostInit();
    }
}
