
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Collections.Generic;

namespace ET
{
    [Config]
    public partial class SkillEffectConfigCategory : Singleton<SkillEffectConfigCategory>
    {
        private readonly Dictionary<int, SkillEffectConfig> _dataMap;
        private readonly List<SkillEffectConfig> _dataList;

        public SkillEffectConfigCategory(ByteBuf _buf)
        {
            _dataMap = new Dictionary<int, SkillEffectConfig>();
            _dataList = new List<SkillEffectConfig>();

            for (int n = _buf.ReadSize(); n > 0; --n)
            {
                SkillEffectConfig _v;
                _v = global::ET.SkillEffectConfig.DeserializeSkillEffectConfig(_buf);
                _dataList.Add(_v);
                _dataMap.Add(_v.Id, _v);
            }

            PostInit();
        }

        public Dictionary<int, SkillEffectConfig> DataMap => _dataMap;
        public List<SkillEffectConfig> DataList => _dataList;

        public SkillEffectConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
        public SkillEffectConfig Get(int key) => _dataMap[key];
        public SkillEffectConfig this[int key] => _dataMap[key];

        partial void PostInit();
    }
}
