
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace ET
{
    [EnableClass]
    public sealed partial class SkillTargetingConfig : BeanBase
    {
        public SkillTargetingConfig(ByteBuf _buf)
        {
            Id = _buf.ReadInt();
            SelectType = _buf.ReadInt();
            MaxTargetCount = _buf.ReadInt();
            CastRange = _buf.ReadFloat();
            EdgeDistance = _buf.ReadFloat();
            UseCollisionRadius = _buf.ReadBool();
            SearchRadius = _buf.ReadFloat();
            SectorAngle = _buf.ReadFloat();
            TargetCampRelation = _buf.ReadInt();
            RequireAlive = _buf.ReadBool();
            SortRule = _buf.ReadInt();
            Desc = _buf.ReadString();

            PostInit();
        }

        public static SkillTargetingConfig DeserializeSkillTargetingConfig(ByteBuf _buf)
        {
            return new SkillTargetingConfig(_buf);
        }

        /// <summary>
        /// 主键
        /// </summary>
        public readonly int Id;

        /// <summary>
        /// 选目标方式
        /// </summary>
        public readonly int SelectType;

        /// <summary>
        /// 最大目标数量
        /// </summary>
        public readonly int MaxTargetCount;

        /// <summary>
        /// 基础施法距离
        /// </summary>
        public readonly float CastRange;

        /// <summary>
        /// 边缘补偿距离
        /// </summary>
        public readonly float EdgeDistance;

        /// <summary>
        /// 是否使用碰撞半径
        /// </summary>
        public readonly bool UseCollisionRadius;

        /// <summary>
        /// 搜索半径
        /// </summary>
        public readonly float SearchRadius;

        /// <summary>
        /// 扇形角度
        /// </summary>
        public readonly float SectorAngle;

        /// <summary>
        /// 目标阵营关系
        /// </summary>
        public readonly int TargetCampRelation;

        /// <summary>
        /// 是否要求目标存活
        /// </summary>
        public readonly bool RequireAlive;

        /// <summary>
        /// 排序规则
        /// </summary>
        public readonly int SortRule;

        /// <summary>
        /// 描述
        /// </summary>
        public readonly string Desc;

        public const int __ID__ = -466752286;

        public override int GetTypeId() => __ID__;

        public override string ToString()
        {
            return "{ "
            + "Id:" + Id + ","
            + "SelectType:" + SelectType + ","
            + "MaxTargetCount:" + MaxTargetCount + ","
            + "CastRange:" + CastRange + ","
            + "EdgeDistance:" + EdgeDistance + ","
            + "UseCollisionRadius:" + UseCollisionRadius + ","
            + "SearchRadius:" + SearchRadius + ","
            + "SectorAngle:" + SectorAngle + ","
            + "TargetCampRelation:" + TargetCampRelation + ","
            + "RequireAlive:" + RequireAlive + ","
            + "SortRule:" + SortRule + ","
            + "Desc:" + Desc + ","
            + "}";
        }

        partial void PostInit();
    }
}
