
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Collections.Generic;

namespace ET
{
    [Config]
    public partial class SkillCastCheckConfigCategory : Singleton<SkillCastCheckConfigCategory>
    {
        private readonly Dictionary<int, SkillCastCheckConfig> _dataMap;
        private readonly List<SkillCastCheckConfig> _dataList;

        public SkillCastCheckConfigCategory(ByteBuf _buf)
        {
            _dataMap = new Dictionary<int, SkillCastCheckConfig>();
            _dataList = new List<SkillCastCheckConfig>();

            for (int n = _buf.ReadSize(); n > 0; --n)
            {
                SkillCastCheckConfig _v;
                _v = global::ET.SkillCastCheckConfig.DeserializeSkillCastCheckConfig(_buf);
                _dataList.Add(_v);
                _dataMap.Add(_v.Id, _v);
            }

            PostInit();
        }

        public Dictionary<int, SkillCastCheckConfig> DataMap => _dataMap;
        public List<SkillCastCheckConfig> DataList => _dataList;

        public SkillCastCheckConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
        public SkillCastCheckConfig Get(int key) => _dataMap[key];
        public SkillCastCheckConfig this[int key] => _dataMap[key];

        partial void PostInit();
    }
}
