
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Collections.Generic;

namespace ET
{
    [Config]
    public partial class SkillTargetingConfigCategory : Singleton<SkillTargetingConfigCategory>
    {
        private readonly Dictionary<int, SkillTargetingConfig> _dataMap;
        private readonly List<SkillTargetingConfig> _dataList;

        public SkillTargetingConfigCategory(ByteBuf _buf)
        {
            _dataMap = new Dictionary<int, SkillTargetingConfig>();
            _dataList = new List<SkillTargetingConfig>();

            for (int n = _buf.ReadSize(); n > 0; --n)
            {
                SkillTargetingConfig _v;
                _v = global::ET.SkillTargetingConfig.DeserializeSkillTargetingConfig(_buf);
                _dataList.Add(_v);
                _dataMap.Add(_v.Id, _v);
            }

            PostInit();
        }

        public Dictionary<int, SkillTargetingConfig> DataMap => _dataMap;
        public List<SkillTargetingConfig> DataList => _dataList;

        public SkillTargetingConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
        public SkillTargetingConfig Get(int key) => _dataMap[key];
        public SkillTargetingConfig this[int key] => _dataMap[key];

        partial void PostInit();
    }
}
