
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace ET
{
    [EnableClass]
    public sealed partial class SkillCastCheckConfig : BeanBase
    {
        public SkillCastCheckConfig(ByteBuf _buf)
        {
            Id = _buf.ReadInt();
            CheckCooldown = _buf.ReadBool();
            CheckCasterAlive = _buf.ReadBool();
            CheckTargetAlive = _buf.ReadBool();
            CheckAutoModeLimit = _buf.ReadBool();
            CheckDistance = _buf.ReadBool();
            CheckCanAttack = _buf.ReadBool();
            FailErrorCode = _buf.ReadInt();
            Desc = _buf.ReadString();

            PostInit();
        }

        public static SkillCastCheckConfig DeserializeSkillCastCheckConfig(ByteBuf _buf)
        {
            return new SkillCastCheckConfig(_buf);
        }

        /// <summary>
        /// 主键
        /// </summary>
        public readonly int Id;

        /// <summary>
        /// 是否检查冷却
        /// </summary>
        public readonly bool CheckCooldown;

        /// <summary>
        /// 是否检查施法者存活
        /// </summary>
        public readonly bool CheckCasterAlive;

        /// <summary>
        /// 是否检查目标存活
        /// </summary>
        public readonly bool CheckTargetAlive;

        /// <summary>
        /// 是否检查自动/手动模式限制
        /// </summary>
        public readonly bool CheckAutoModeLimit;

        /// <summary>
        /// 是否检查距离
        /// </summary>
        public readonly bool CheckDistance;

        /// <summary>
        /// 是否检查是否可攻击
        /// </summary>
        public readonly bool CheckCanAttack;

        /// <summary>
        /// 失败错误码
        /// </summary>
        public readonly int FailErrorCode;

        /// <summary>
        /// 描述
        /// </summary>
        public readonly string Desc;

        public const int __ID__ = 288195386;

        public override int GetTypeId() => __ID__;

        public override string ToString()
        {
            return "{ "
            + "Id:" + Id + ","
            + "CheckCooldown:" + CheckCooldown + ","
            + "CheckCasterAlive:" + CheckCasterAlive + ","
            + "CheckTargetAlive:" + CheckTargetAlive + ","
            + "CheckAutoModeLimit:" + CheckAutoModeLimit + ","
            + "CheckDistance:" + CheckDistance + ","
            + "CheckCanAttack:" + CheckCanAttack + ","
            + "FailErrorCode:" + FailErrorCode + ","
            + "Desc:" + Desc + ","
            + "}";
        }

        partial void PostInit();
    }
}
