
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace ET
{
    [EnableClass]
    public sealed partial class StageConfig : BeanBase
    {
        public StageConfig(ByteBuf _buf)
        {
            Id = _buf.ReadInt();
            Name = _buf.ReadString();
            Type = _buf.ReadInt();
            TotalWaves = _buf.ReadInt();
            {int __n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);WaveList = new int[__n0];for(var __index0 = 0 ; __index0 < __n0 ; __index0++) { int __e0;__e0 = _buf.ReadInt(); WaveList[__index0] = __e0;}}
            Reward = _buf.ReadInt();
            TimeLimit = _buf.ReadInt();

            PostInit();
        }

        public static StageConfig DeserializeStageConfig(ByteBuf _buf)
        {
            return new StageConfig(_buf);
        }

        /// <summary>
        /// Id
        /// </summary>
        public readonly int Id;

        /// <summary>
        /// Name
        /// </summary>
        public readonly string Name;

        /// <summary>
        /// Type
        /// </summary>
        public readonly int Type;

        /// <summary>
        /// TotalWaves
        /// </summary>
        public readonly int TotalWaves;

        /// <summary>
        /// WaveList
        /// </summary>
        public readonly int[] WaveList;

        /// <summary>
        /// Reward
        /// </summary>
        public readonly int Reward;

        /// <summary>
        /// TimeLimit
        /// </summary>
        public readonly int TimeLimit;

        public const int __ID__ = 1215177664;

        public override int GetTypeId() => __ID__;

        public override string ToString()
        {
            return "{ "
            + "Id:" + Id + ","
            + "Name:" + Name + ","
            + "Type:" + Type + ","
            + "TotalWaves:" + TotalWaves + ","
            + "WaveList:" + Luban.StringUtil.CollectionToString(WaveList) + ","
            + "Reward:" + Reward + ","
            + "TimeLimit:" + TimeLimit + ","
            + "}";
        }

        partial void PostInit();
    }
}
