
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Collections.Generic;

namespace ET
{
    [Config]
    public partial class UnitCombatConfigCategory : Singleton<UnitCombatConfigCategory>
    {
        private readonly Dictionary<int, UnitCombatConfig> _dataMap;
        private readonly List<UnitCombatConfig> _dataList;

        public UnitCombatConfigCategory(ByteBuf _buf)
        {
            _dataMap = new Dictionary<int, UnitCombatConfig>();
            _dataList = new List<UnitCombatConfig>();

            for (int n = _buf.ReadSize(); n > 0; --n)
            {
                UnitCombatConfig _v;
                _v = global::ET.UnitCombatConfig.DeserializeUnitCombatConfig(_buf);
                _dataList.Add(_v);
                _dataMap.Add(_v.Id, _v);
            }

            PostInit();
        }

        public Dictionary<int, UnitCombatConfig> DataMap => _dataMap;
        public List<UnitCombatConfig> DataList => _dataList;

        public UnitCombatConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
        public UnitCombatConfig Get(int key) => _dataMap[key];
        public UnitCombatConfig this[int key] => _dataMap[key];

        partial void PostInit();
    }
}

