
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace ET
{
    [EnableClass]
    public sealed partial class UnitCombatConfig : BeanBase
    {
        public UnitCombatConfig(ByteBuf _buf)
        {
            Id = _buf.ReadInt();
            ConfigId = _buf.ReadInt();
            NormalAttackSkillId = _buf.ReadInt();
            {int __n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);AutoSkillIds = new int[__n0];for(var __index0 = 0 ; __index0 < __n0 ; __index0++) { int __e0;__e0 = _buf.ReadInt(); AutoSkillIds[__index0] = __e0;}}
            AutoBattleStrategyId = _buf.ReadInt();
            MoveSpeed = _buf.ReadFloat();
            AutoCastNormalAttack = _buf.ReadBool();
            DefaultTargetPolicy = _buf.ReadString();
            Desc = _buf.ReadString();

            PostInit();
        }

        public static UnitCombatConfig DeserializeUnitCombatConfig(ByteBuf _buf)
        {
            return new UnitCombatConfig(_buf);
        }

        /// <summary>
        /// 主键
        /// </summary>
        public readonly int Id;

        /// <summary>
        /// 战斗单位配置ID（可对应UnitConfig或MonsterUnitConfig）
        /// </summary>
        public readonly int ConfigId;

        /// <summary>
        /// 默认普攻技能ID
        /// </summary>
        public readonly int NormalAttackSkillId;

        /// <summary>
        /// 默认普攻技能ID
        /// </summary>
        public SkillConfig NormalAttackSkillIdConfig => SkillConfigCategory.Instance.GetOrDefault(NormalAttackSkillId);

        /// <summary>
        /// AI自动择优技能列表（为空则回退普攻）
        /// </summary>
        public readonly int[] AutoSkillIds;

        /// <summary>
        /// 自动战斗策略配置ID
        /// </summary>
        public readonly int AutoBattleStrategyId;

        /// <summary>
        /// 自动战斗策略配置ID
        /// </summary>
        public AutoBattleStrategyConfig AutoBattleStrategyIdConfig => AutoBattleStrategyConfigCategory.Instance.GetOrDefault(AutoBattleStrategyId);

        /// <summary>
        /// 移动速度（米/秒）
        /// </summary>
        public readonly float MoveSpeed;

        /// <summary>
        /// 是否自动释放普攻
        /// </summary>
        public readonly bool AutoCastNormalAttack;

        /// <summary>
        /// 默认目标策略
        /// </summary>
        public readonly string DefaultTargetPolicy;

        /// <summary>
        /// 描述
        /// </summary>
        public readonly string Desc;

        public const int __ID__ = 1584771866;

        public override int GetTypeId() => __ID__;

        public override string ToString()
        {
            return "{ "
            + "Id:" + Id + ","
            + "ConfigId:" + ConfigId + ","
            + "NormalAttackSkillId:" + NormalAttackSkillId + ","
            + "AutoSkillIds:" + Luban.StringUtil.CollectionToString(AutoSkillIds) + ","
            + "AutoBattleStrategyId:" + AutoBattleStrategyId + ","
            + "MoveSpeed:" + MoveSpeed + ","
            + "AutoCastNormalAttack:" + AutoCastNormalAttack + ","
            + "DefaultTargetPolicy:" + DefaultTargetPolicy + ","
            + "Desc:" + Desc + ","
            + "}";
        }

        partial void PostInit();
    }
}
